#!/usr/bin/env python3

def fib(n):
    "docstring"
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)



i = 1
sum = 0

while (fib(i)) < 4000000:
    if (fib(i) % 2) == 0:
        sum+=fib(i)
    i+=1

print(sum, " ", i)
