#!/usr/bin/env python3

import math

def isPrime(n):
    sqrtN = math.ceil(math.sqrt(n))
    if n % 2 == 0:
        return False
    i = 3
    while i <= sqrtN:
        if n % i == 0:
            return False   
        i+=2
    return True

def prime_sieve(limit):
    list = []
    for i in range(1, limit):
        if isPrime(i):
            list.append(i)
    return list
    
    
    
def highestPrime(n):
    sqrtN = math.ceil(math.sqrt(n))
    ans = 0
    
    for p in prime_sieve(sqrtN):
        if n % p == 0:
            ans = p
    
    return ans
    
    
    
print(highestPrime(600851475143))
