#!/usr/bin/env python3

def isPalindrome(s):
    length = len(s)
    if(length == 1) or (length == 0):
        return True
    elif (s[0]) == (s[-1]):
        return isPalindrome(s[1:-1])
    else:
        return False
        
 
def multiply3Digits():
    s = 0
    for i in range(100,1000):
        for j in range(100,1000):
            ixj = i * j
            ##print(i, " ", j)
            if isPalindrome(str(ixj)) and s < ixj:
                s = ixj
    return s
        
        
        
        
 
print(multiply3Digits())
