#!/usr/bin/env python3
def sumOfSquares(r):
    sum = 0
    for i in range(1, r+1):
        sum += i**2
    return sum
    
def squareOfSum(r):
    sum = 0
    for i in range(1, r+1):
        sum += i
    return sum**2
    
print(sumOfSquares(100) - squareOfSum(100))
