#!/usr/bin/env python3

import math

def isPrime(n):
    sqrtN = math.ceil(math.sqrt(n))
    if n % 2 == 0:
        return False
    i = 3
    while i <= sqrtN:
        if n % i == 0:
            return False   
        i+=2
    return True
    
count = 0
potential = 1

while count < 10001:
    if isPrime(potential):
        count+=1
    potential+=2

print(potential - 2)
